ALTER TABLE "suppliers" RENAME COLUMN "villageId" TO "village_id";--> statement-breakpoint
ALTER TABLE "suppliers" DROP CONSTRAINT "suppliers_villageId_villages_id_fk";
--> statement-breakpoint
ALTER TABLE "districts" ALTER COLUMN "id" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "districts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "districts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "regencies" ALTER COLUMN "id" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "regencies" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "regencies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "villages" ALTER COLUMN "id" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "villages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "villages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "suppliers" ADD CONSTRAINT "suppliers_village_id_villages_id_fk" FOREIGN KEY ("village_id") REFERENCES "public"."villages"("id") ON DELETE cascade ON UPDATE no action;