export const MAX_PHOTO_FILE_SIZE_MB = 1
export const MAX_PHOTO_FILE_SIZE_BYTES = MAX_PHOTO_FILE_SIZE_MB * 1024 * 1024
export const MAX_PHOTO_FILE_COUNT = 10
export const MAX_PHOTO_UPLOAD_SIZE_BYTES =
  MAX_PHOTO_FILE_COUNT * MAX_PHOTO_FILE_SIZE_BYTES
